### ISSUE TITLE
BL.3: Predicate mapping framework and implementation

### ISSUE THREAD

**Issue by tursynay** [TranslatorIIPrototypes/operations#6]
**Issue Description:**
Create framework for predicate mapping that extends the existing pairwise mappings, to allow for contextual mapping (e.g., if the predicate is ‘increases’, and this connects a gene to a disease, map to ‘increases risk of’). Curate mappings for the 10,000+ source predicates gathered in the first phase of Translator using a combination of consortium-wide crowdsourcing and expert curation. 
 https://github.com/biolink/biolink-model/issues/285, 
https://github.com/biolink/biolink-model/issues/286

**Comment by RichardBruskiewich** [comment]
Roger this @tursynay. This task has the largest budget item assigned to STAR and the one likely involving most biomedical-specific knowledge thus I am justifiably the primary assignee. That said, I will again need to review specific expectations with @cmungall (not sure who else is funded to work on this...), clarify specific expectations and likely also confer with Matt Brush since he was heavily engaged in the NCATS Feasibility work in this topic (not sure, though, what Matt's FTE is on NCATS Development phase, SRI or otherwise...I haven't chatted with him recently).

**Comment by tursynay** [comment]
Thank you for the feedback. 

Tursynay

**Comment by tursynay** [comment]
moving to the new org: https://github.com/TranslatorSRI/Operations/issues/13
