### ISSUE TITLE
BL.5: Implement views

### ISSUE THREAD

**Issue by tursynay** [TranslatorIIPrototypes/operations#8]
**Issue Description:**
Implement alternate views/perspectives in the model, and define computable transformations between them; e.g., between interaction-centric views and pathway-centric views. See https://github.com/biolink/biolink-model/issues/284

**Comment by tursynay** [comment]
Hi Richard,

Assigning this issue to you. Please let me know if there is another person who make sense to have this issue assigned.

Tursynay

**Comment by RichardBruskiewich** [comment]
Hi @tursynay, @cmungall has assigned a budget to my STAR team to participate in this activity. Given the nature of the activity, which is UI-centric, I will likely engage my team-mate (and son), Kenneth Huellas-Bruskiewicz in some of the work, since he has good recent experience with user interface development. Please add him to the repository (he is already registered with the NCATS Development project, but does not seem to be in the TranslatorIIPrototypes Github organization) and co-assign him to this task (I can still be listed there as well).  Both of us will take our cue from Chris (and Deepak?). Thanks!

**Comment by tursynay** [comment]
Sounds good. I will get Kenneth invited to the site and assigned here. Could you provide Kenneth's GH handle?

**Comment by RichardBruskiewich** [comment]
@tursynay, Kenneth's GH handle is '**kbruskiewicz**'.

**Comment by tursynay** [comment]
moved to the new org: https://github.com/TranslatorSRI/Operations/issues/15
